# This is a basic workflow to help you get started with Actions

name: getting-started

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows the workflow to be manually triggered
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      myvalue: ${{ steps.set-output.outputs.myvalue }}
    steps:
      - name: Set an output value
        id: set-output
        run: echo "myvalue=hello" >> $GITHUB_OUTPUT

  matrix-job:
    needs: generate-output
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Use output from previous job
        run: echo "${{ needs.generate-output.outputs.myvalue }}-${{ matrix.number }}"

  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download
  
  Test:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./... -v

  simple:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script with secret
        run: echo ${{ secrets.MY_SECRET_PASSWORD }}